version: '3'

services:
  db:
    image: qaprosoft/postgres:9.6
    volumes:
     - ./pgdata:/var/lib/postgresql/data
     - ./database/:/docker-entrypoint-initdb.d
    ports:
     - 5433:5432
    env_file:
     - integrations.env
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    restart: always
  rabbitmq:
    image: qaprosoft/rabbitmq:latest
    ports:
     - 15672:15672
     - 15674:15674
     - 5672:5672
    volumes:
     - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
    environment:
     - RABBITMQ_DEFAULT_USER=qpsdemo
     - RABBITMQ_DEFAULT_PASS=qpsdemo
    restart: always
  screenshoter:
    image: selenium/standalone-chrome:latest
    volumes:
    - /dev/shm:/dev/shm
    restart: always
  elk:
    image: sebp/elk:630
    volumes:
     - ./config/logstash.conf:/etc/logstash/conf.d/logstash.conf
     - ./config/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
     - ./esdata:/var/lib/elasticsearch
    ports:
     - 5601:5601
     - 9200:9200
     - 5044:5044
    depends_on:
     - "rabbitmq"
    restart: always
  zafira:
    image: qaprosoft/zafira:latest
    ports:
     - 8080:8080
    env_file:
     - integrations.env
    environment:
     - ZAFIRA_URL=http://localhost:8080
     - ZAFIRA_USER=qpsdemo
     - ZAFIRA_PASS=qpsdemo
     - ZAFIRA_JDBC_URL=jdbc:postgresql://db:5432/postgres
     - ZAFIRA_JDBC_USER=postgres
     - ZAFIRA_JDBC_PASS=postgres
     - ZAFIRA_SELENIUM_URL=http://screenshoter:4444/wd/hub
     - ZAFIRA_ELASTICSEARCH_URL=http://localhost:9200
    depends_on:
     - "db"
     - "rabbitmq"
     - "screenshoter"
    restart: always
