version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
     - ./pgdata:/var/lib/postgresql/data
     - ./database/initdb.d/:/docker-entrypoint-initdb.d
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    restart: always
  zafira:
    image: qaprosoft/zafira:rabbit
    ports:
     - "8080:8080"
    environment:
     - ZAFIRA_URL=http://localhost:8080
     - ZAFIRA_USER=admin
     - ZAFIRA_PASS=qaprosoft
     - ZAFIRA_JDBC_URL=jdbc:postgresql://db:5432/postgres
     - ZAFIRA_JDBC_USER=postgres
     - ZAFIRA_JDBC_PASS=postgres
    depends_on:
     - "db"
    restart: always
