version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
     - ./db:/var/lib/postgresql
     - ./database/db-pg.sh:/docker-entrypoint-initdb.d/1-init.sh
     - ./database/db-data.sh:/docker-entrypoint-initdb.d/2-init.sh
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    restart: always
  zafira:
    image: qaprosoft/zafira:latest
    ports:
     - "8080:8080"
    environment:
     - ZAFIRA_URL=http://localhost:8080
     - ZAFIRA_USER=admin
     - ZAFIRA_PASS=qaprosoft
     - ZAFIRA_JDBC_URL=jdbc:postgresql://db:5432/postgres
     - ZAFIRA_JDBC_USER=postgres
     - ZAFIRA_JDBC_PASS=postgres
    depends_on:
     - "db"
    restart: always
