site_name: Zafira
pages:
    - Overview: index.md
    - Getting started: getting_started.md
    - Release notes: releases.md
    - About: about.md
theme:
  name: 'material'
repo_url: https://github.com/qaprosoft/zafira
repo_name: Github
